language: go

before_install:
  - go get github.com/mattn/goveralls

go:
  - 1.7

env:
  global:
    secure: PnuftkgEkQ4O5U3TLRJ4obEwRZ7nBG91EL828NCW4x8kq6WzpjJa59WVHfwO25kKmVqRBZOedCLsdrtetaTUMT/uTt3z6KI52+iViKab/i4tMvUZLD/Y3VNEE5if6FtXJ+9SAe/Df66jri84slejpCRvvCl+m1ipBSpLm5i3ASAyXTP/YAeNPSR6Q7d0apr3r6w33Mi6K3tlPBaWqRd9wEMvGvyrCFi7oqqxWwvjOm5D8pOYkkeU0xNztTK8tFQEQPl9A3FKiK+NpRUokpOpH9+QRWZ843/8RV3IYv3OQBbTFFMaAYJCQLtYhR87gJWTd4NtqioEtMv2biKoIU+3x9+utUPCS8QVMIObmVzLGzzLahrazlTmzXMvon5ejm70Rywe3Qp4hwXkT5R3OwZKTk40RSR49KOS8Hnjpe253qNV25ibVjR82BsJd9xx3NABIA7e2QyiJNOgyfAiG9iItUJ2kZobgs0SOENbfbuoAayA0hi0dEbMTiHyO+9KSZOHBz6qZEsZyAI036msqQrKCj890+e8pdCExhpXV4kLHjIdQneVCbXsGvwTqJdufifotaE+1foX1QEb0Fsv62Tp/VfO/X4WFWqy1b++gg4NBzX/gW3PO6tKXluqVHSWe5t6ticE7Tux4FE0AhvlciN2dtQV1WCgtRGk4X3/7vnp/hA=
