language: go

before_install:
  - go get github.com/mattn/goveralls

go:
            - 1.7

secure: "LA5akE9ZnyJKNGJTCGCvulkrU7hy15i1VobluHtpF2c+gzZ4ZmXDh3covh3XdEDb7rOXX5gLRFmYWQ3Mo248HTaNqfuHmINN6atapYVtG0OtkbLoK0WlQu0UDdAY0WPP0YhmubKBxAw/l7RgUDWnAq/lnUIm9tLphLIbKnv5GKGGa6t/NgBp8eN5Slnqy9TpRu2313U6JlNv9fNTFcJkIlhWMsUpcqC6ipaeWYkfMUjEqrzQ/RRk3qewCtmAh/P7R1WZWL0vle3BzhWvVJOJd98az1cKEuOuv397qWv17mfCQ78Pz55J0kBXeBciPqWKINJl5ELg6tTe3b8o8Agx5YzbsWLpBzNd1bIwSTT7TvgNQy+BrHzuDquhsBJQiq/RC1PB5aM/njghEU9nFHDEyWEk1gqLsZhATikV8aif+UKn1Ec3P2w4NcwKBj/SHAtPykEti4KjaIZnr5Oz0uTsvpmLcn4imING/TkvSPzrPh44YjuBc3q1lfaXhLf0W3zvpzlunZxdEwWlJ3UTLDg76HlXSE52q3uGwrM59244ePxnOrMKa4jJereQ8V0PX+wdjZECsm7zbmIHk9BJ86lozmR5iDcqOUmBg8QcbKSZnwYNf3J+j0g7i6pV5LOX/o0EnUkaQS0NYXIPR9QaJiihYp/SftxqM8O9vxDAaghLabM="